name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  token: 
    required: true
    description: 'input description here'
    default: 'default value if applicable'
  repo:
    required: false
    description: 'repository name i.e. owner/repo-name format'
    default: ${{ github.repository }}
runs:
  using: 'node12'
  main: 'dist/index.js'
